# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          # このコンテナにdatabase,user,passwordを作成する
          POSTGRES_DB: db-name
          POSTGRES_USER: user-name
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      # データベースコンテナにアクセスする。アクセスするときは、envで設定したものを利用。
      DATABASE_URL: "postgres://user-name:password@localhost:5432/db-name"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1 # v1.146.0
        with:
          # 以前、github actionsでインストールしたbundleをcacheしており、それを使う。
          bundler-cache: true
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:migrate
      # Add or replace test runners here
      - name: Run tests
        run: bundle exec rspec